name: Deploy operations
# Hello

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*
      - master
      - dev
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running tests
        run: echo "Running tests..."

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building
        run: echo "Building..."

  deploy:
    if: startsWith(github.ref_name, 'refs/head/feature/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploying
        run: echo 'Deploying...'
