name: Deploy operations
# Hello

on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - bugfix/*
      - chore/*
      - docs/*
  pull_request:
    branches:
      - dev
      - master
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running tests
        run: echo "Running tests..."

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building
        run: |
          echo Building...

  feature-deploy:
    if: ${{ (!startsWith(github.ref, 'refs/heads/dev') && !startsWith(github.ref, 'refs/heads/master')) && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploying
        run: |
          echo Deploying...

  staging-deploy:
    if: startsWith(github.ref, 'refs/heads/dev')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploying to staging
        run: echo Deploying to staging

  production-deploy:
    if: startsWith(github.ref, 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploying to production
        run: echo Deploying to production
