name: Deploy operations
# Hello

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - feature/*
      - master
      - dev
    types: [closed]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running tests
        run: echo "Running tests..."

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building
        run: |
          echo Building...
          echo ${{ github.ref }}
          echo ${{ github.event_name }}
          echo ${{ github.event.pull_request.merged }}

  feature-deploy:
    if: startsWith(github.ref, 'refs/heads/feature/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploying
        run: |
          echo Deploying...
          echo ${{ github.ref }}
          echo ${{ github.event_name }}

  cleanup-feature:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cleaning up feature
        run: |
          echo Cleaning...
